name: km_dollar_backend
description: Backend Dart com Shelf para o app KM$ (Motouber)
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0
  logging: ^1.2.0
  sqlite3: ^2.4.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.13.0

dev_dependencies:
  lints: ^3.0.0
